networks:
  defaullt:
    external: true
      name: roboshop
services:
  #docker run -d --name mongodb mongodb:1
  mongodb: 
    image: mongodb:1
    

  catalogue: 
    image: catalogue:1
    depends_on:
    - mongodb
    
  web:
    image: web:1
    ports: 
    - "80:80"
    depends_on:
    - catalogue
