networks:
  defaullt:
    external:
      name: roboshop
services:
  #docker run -d --name mongodb mongodb:1
  mongodb: 
    image: mongodb:1
    networks:
    - roboshop

  catalogue: 
    image: catalogue:1
    
  web:
    image: web:1
    ports: 
    - "80:80"
    depends_on:
