networks:
  defaullt:
    external: true
    name: roboshop
services:
  #docker run -d --name mongodb mongodb:1
  mongodb: 
    image: mongodb:1
    

  catalogue: 
    image: catalogue:1
    depends_on:
    - mongodb
    
  web:
    image: web:1
    ports: 
    - "80:80"
    depends_on:
    - catalogue

  redis:
  image: redis


  user:
  image: user:v1
  depends_on: 
  - redis
  - mongodb

  cart:
  image: cart:v1
  depends_on: 
  - redis
  - catalogue
